ARTIST="Mark Greaney" # or writer of the book
ALBUM="Tom Clancy Full Force and Effect (A Jack Ryan Novel)" # or titel of the book
SUMMARY="A North Korean ICBM crashes into the Sea of Japan. A veteran CIA officer is murdered in Ho Chi Minh City, and a package of forged documents goes missing. The pieces are there, but assembling the puzzle will cost Jack Ryan, Jr. and his fellow Campus agents precious time. Time they don’t have."
LINK="http://guu.st/Audiobooks"
COPYRIGHT="&#x2117; &amp; &#xA9; 2000-2014 CousinCocaine"
SUBTITLE="A Jack Ryan Novel"
OWNERNAME="CousinCocaine"
OWNEREMAIL="CousinCocaine@medicode.nl"
IMGURL="" # convert input.jpg -gravity center -background white -resize 1400x1400 -extent 1400x1400 cover.jpg 
CATEGORY="Fiction" # see https://rss.itunes.apple.com for categories
